### PR TITLE
Remove KProxy

### PR DESCRIPTION
**Pull request by int-index**
Remove kind proxies from `singletons`.

### CODE REVIEW

**Comment by int-index** [comment]
I am now stuck due to what I believe to be a bug in GHC.

In the `defunctionalize` function we create `KindInference` constructors, each holding an evidence that the kinds match. This evidence is currently in the form `('KProxy :: KProxy k1) ~ ('KProxy :: KProxy k2)`. However, if I change it to `k1 ~ k2` (by defining `type KindOf (a :: k) = k`), I get mysterious errors:

```
[31 of 50] Compiling Data.Singletons.Prelude.Base ( src/Data/Singletons/Prelude/Base.hs, dist/build/Data/Singletons/Prelude/Base.o ) [Data.Singletons changed]

src/Data/Singletons/Prelude/Base.hs:55:3: error:
    • Could not deduce: k1 ~ a0
      from the context: (t0 ~ f0, t1 ~ g0, t2 ~ a_16278989530)
        bound by the type signature for:
                   lambda_a28se :: (t0 ~ f0, t1 ~ g0, t2 ~ a_16278989530) =>
                                   Sing f0
                                   -> Sing g0
                                   -> Sing a_16278989530
                                   -> Sing (Apply (Apply (Apply (:.$) t0) t1) t2)
        at src/Data/Singletons/Prelude/Base.hs:(55,3)-(92,3)
      ‘k1’ is a rigid type variable bound by
        the type signature for:
          lambda_a28si :: forall k k1 (x0 :: k1).
                          Sing x0
                          -> Sing
                               (Apply
                                  (Apply (Apply (Apply Lambda_1627898958Sym0 f0) g0) a_16278989530)
                                  x0)
        at src/Data/Singletons/Prelude/Base.hs:55:3
      ‘a0’ is a rigid type variable bound by
        the type signature for:
          (%:.) :: forall b0 c0 a0 (t0 :: TyFun b0 c0
                                          -> ghc-prim-0.5.0.0:GHC.Types.Type) (t1 :: TyFun a0 b0
                                                                                     -> ghc-prim-0.5.0.0:GHC.Types.Type) (t2 :: a0).
                   Sing t0
                   -> Sing t1
                   -> Sing t2
                   -> Sing (Apply (Apply (Apply (:.$) t0) t1) t2)
        at src/Data/Singletons/Prelude/Base.hs:55:3
      Expected type: Sing x0
        Actual type: Sing x0
    • In the second argument of ‘applySing’, namely ‘x_a28sj’
      In the second argument of ‘applySing’, namely
        ‘applySing g_a28sg x_a28sj’
      In the expression: applySing f_a28sf (applySing g_a28sg x_a28sj)
    • Relevant bindings include
        x_a28sj :: Sing x0
          (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        lambda :: Sing x0
                  -> Sing
                       (Apply
                          (Apply (Apply (Apply Lambda_1627898958Sym0 f0) g0) a_16278989530)
                          x0)
          (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        sX :: Sing t (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        a_1627898953_a28sh :: Sing a_16278989530
          (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        g_a28sg :: Sing g0
          (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        lambda :: Sing f0
                  -> Sing g0
                  -> Sing a_16278989530
                  -> Sing (Apply (Apply (Apply (:.$) t0) t1) t2)
          (bound at src/Data/Singletons/Prelude/Base.hs:55:3)
        (Some bindings suppressed; use -fmax-relevant-binds=N or -fno-max-relevant-binds)
```

I expect `k1 ~ k2` to be a more direct way to express the same thing as `('KProxy :: KProxy k1) ~ ('KProxy :: KProxy k2)`. Is there anything I'm missing?

cc @goldfirere

**Comment by int-index** [comment]
I haven't managed to get rid of `KProxy` in promoted classes because of errors that I couldn't decipher.

**Comment by int-index** [comment]
Kind proxies gone! There are two things left to be done:

* Remove regular `Proxy` from `KindOf`
* Remove regular `Proxy` from promoted classes.

**Comment by int-index** [comment]
I believe this PR is mergeable as is. Perhaps someone more knowledgeable than me can solve the remaining issues.

**Comment by goldfirere** [comment]
Wow. Thanks! Did you ever figure out what was going on with those error messages? Or did you just work around? Will review right now.

**Comment by int-index** [comment]
> Did you ever figure out what was going on with those error messages? Or did you just work around?

After some staring at `-ddump-splices` output I decided to work-around by using regular `Proxy` instead of `KProxy` (the original intention was to use no proxies at all).

**Comment by goldfirere** [comment]
This is wonderful. Looking into the error above. Regardless, will push officially accept this PR shortly.

**Comment by goldfirere** [comment]
... and THANKS!

**Comment by goldfirere** [comment]
There are two lingering uses of `Proxy`:
1. In `KindOf`. This is used only to stimulate kind inference in the `KindInference` data constructors. After quite a bit of staring at it all, this is expected behavior. When GHC sees a user-written `(t1 ~ t2)` constraint, it certainly doesn't try to unify `t1` and `t2`. But it does try to unify their kinds. So we really want the action to happen "one level up". I did try to simplify, by using `('Proxy :: Proxy (KindOf ...))`. and choosing `KindOf (a :: k) = k`. This failed, due to goldfirere/ghc#68. So I made no change here.

2. In promoted (but not singled) classes. See #149.

**Comment by int-index** [comment]
Alright, thank you for looking into this!

**Pull request merged**
